version: '3.5'

services:
  app:
    build:
      context: ./
      target: development
    restart: unless-stopped
    volumes:
      - .:/usr/local/app
    command: yarn start:dev
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - mailhog
  mysql:
    image: 'mysql:5.7'
    restart: unless-stopped
    ports:
      - '3305:3306'
    env_file:
      - .env.docker
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --max_allowed_packet=32505856
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
  mailhog:
    image: 'mailhog/mailhog'
    restart: unless-stopped
    ports:
      - '1026:1025'
      - '8026:8025'